# Site settings
title: Outsky
email: xxx@qq.com
description: > # this means to ignore newlines until "baseurl:"
    Outsky's personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://outsky.org" # the base hostname & protocol for your site
github_username:  outsky
permalink: none

# Build settings
markdown: kramdown
